// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDexkGcL5Or1KM90sxd3FCmZ8XLDexHCic',
    appId: '1:1045028490021:web:b1f1e6e78f4937cb5b68cc',
    messagingSenderId: '1045028490021',
    projectId: 'whether-app-login',
    authDomain: 'whether-app-login.firebaseapp.com',
    storageBucket: 'whether-app-login.firebasestorage.app',
    measurementId: 'G-DZGL888P1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh4xTFnC3UJV9HwRfAgChFwVzDAeeUcwM',
    appId: '1:1045028490021:android:5e54a8507deff31a5b68cc',
    messagingSenderId: '1045028490021',
    projectId: 'whether-app-login',
    storageBucket: 'whether-app-login.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAx5_G-KlZOfh-bKwE-6IEHbIzKcRBApxs',
    appId: '1:1045028490021:ios:7f34429b62381c1b5b68cc',
    messagingSenderId: '1045028490021',
    projectId: 'whether-app-login',
    storageBucket: 'whether-app-login.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAx5_G-KlZOfh-bKwE-6IEHbIzKcRBApxs',
    appId: '1:1045028490021:ios:7f34429b62381c1b5b68cc',
    messagingSenderId: '1045028490021',
    projectId: 'whether-app-login',
    storageBucket: 'whether-app-login.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDexkGcL5Or1KM90sxd3FCmZ8XLDexHCic',
    appId: '1:1045028490021:web:2f9414af49a88c705b68cc',
    messagingSenderId: '1045028490021',
    projectId: 'whether-app-login',
    authDomain: 'whether-app-login.firebaseapp.com',
    storageBucket: 'whether-app-login.firebasestorage.app',
    measurementId: 'G-Q24XVMC0DH',
  );
}
